chore(ci): ppo workflow runs on volcanoengine machine learning platform

diff --git a/.github/workflows/e2e_ppo_trainer_megatron.yml b/.github/workflows/e2e_ppo_trainer_megatron.yml
--- a/.github/workflows/e2e_ppo_trainer_megatron.yml
+++ b/.github/workflows/e2e_ppo_trainer_megatron.yml
@@ -1,4 +1,4 @@
-name: e2e_ppo_trainer_megatron
+name: e2e_ppo_trainer_megatron_1
 # latest version: Megatron-LM core_r0.11.0 https://github.com/NVIDIA/Megatron-LM/tree/core_r0.11.0
 
 on:
@@ -8,6 +8,7 @@ on:
     branches:
       - main
       - v0.*
+      - feat/ppo_workflow_test
   pull_request:
     branches:
       - main
@@ -40,9 +41,38 @@ concurrency:
 permissions:
   contents: read
 
+env:
+  IMAGE: "verl-ci-cn-beijing.cr.volces.com/whatcanyousee/verl:ngc-cu124-vllm0.8.5-sglang0.4.6.post5-mcore0.12.0-te2.3"
+  DYNAMIC_RUNNER_ENDPOINT: "https://sd10g3clalm04ug7alq90.apigateway-cn-beijing.volceapi.com/runner"
+
 jobs:
+  setup:
+    runs-on: ubuntu-latest
+    outputs:
+      runner-label: ${{ steps.create-runner.outputs.runner_label }}
+      mlp-task-id: ${{ steps.create-runner.outputs.mlp_task_id }}
+    steps:
+      - name: create runner
+        id: create-runner
+        run: |
+          # 调用faas创建runner环境
+          resp=$(curl -X POST "${{ env.DYNAMIC_RUNNER_ENDPOINT }}/create-test" \
+          -d '{"Image": "${{ env.IMAGE }}"}')
+          echo $resp
+          runner_label=$(echo $resp | jq -r '.runner_label')
+          echo $runner_label
+          if [[ -z $runner_label || $runner_label == "null" ]]; then
+            echo "create runner failed"
+            exit 1
+          fi
+          echo "runner_label=$runner_label" >> $GITHUB_OUTPUT   
+          mlp_task_id=$(echo $resp | jq -r '.task_id')
+          echo "mlp_task_id=$mlp_task_id" >> $GITHUB_OUTPUT 
+          exit 1
+
   e2e_ppo_trainer_megatron-deepseek:
-    runs-on: [L20x8]
+    needs: setup
+    runs-on: ["${{ needs.setup.outputs.runner-label }}"]
     timeout-minutes: 60 # Increase this timeout value as needed
     env:
       HTTP_PROXY: ${{ secrets.PROXY_HTTP }}
@@ -50,9 +80,6 @@ jobs:
       NO_PROXY: "localhost,127.0.0.1,hf-mirror.com"
       HF_ENDPOINT: "https://hf-mirror.com"
       HF_HUB_ENABLE_HF_TRANSFER: "0" # This is more stable
-    container:
-      image: whatcanyousee/verl:ngc-cu124-vllm0.8.5-sglang0.4.6.post5-mcore0.12.0-te2.3
-      options: --gpus all --shm-size=10g
     steps:
       - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
         with:
@@ -84,7 +111,8 @@ jobs:
         run: |
           rm -rf checkpoints
   e2e_ppo_trainer_megatron-qwen3:
-    runs-on: [L20x8]
+    needs: setup
+    runs-on: ["${{ needs.setup.outputs.runner-label }}"]
     timeout-minutes: 60 # Increase this timeout value as needed
     env:
       HTTP_PROXY: ${{ secrets.PROXY_HTTP }}
@@ -92,9 +120,6 @@ jobs:
       NO_PROXY: "localhost,127.0.0.1,hf-mirror.com"
       HF_ENDPOINT: "https://hf-mirror.com"
       HF_HUB_ENABLE_HF_TRANSFER: "0" # This is more stable
-    container:
-      image: whatcanyousee/verl:ngc-cu124-vllm0.8.5-sglang0.4.6.post5-mcore0.12.0-te2.3
-      options: --gpus all --shm-size=10g
     steps:
       - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
         with:
@@ -123,7 +148,8 @@ jobs:
         run: |
           rm -rf checkpoints
   e2e_ppo_trainer_megatron-different-train-infer-tp-qwen-tie-embedding:
-    runs-on: [L20x8]
+    needs: setup
+    runs-on: ["${{ needs.setup.outputs.runner-label }}"]
     timeout-minutes: 60 # Increase this timeout value as needed
     env:
       HTTP_PROXY: ${{ secrets.PROXY_HTTP }}
@@ -131,9 +157,6 @@ jobs:
       NO_PROXY: "localhost,127.0.0.1,hf-mirror.com"
       HF_ENDPOINT: "https://hf-mirror.com"
       HF_HUB_ENABLE_HF_TRANSFER: "0" # This is more stable
-    container:
-      image: whatcanyousee/verl:ngc-cu124-vllm0.8.5-sglang0.4.6.post5-mcore0.12.0-te2.3
-      options: --gpus all --shm-size=10g
     steps:
       - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
         with:
@@ -156,7 +179,8 @@ jobs:
         run: |
           rm -rf checkpoints
   e2e_ppo_trainer_megatron-qwen-override-transformer-config:
-    runs-on: [L20x8]
+    needs: setup
+    runs-on: ["${{ needs.setup.outputs.runner-label }}"]
     timeout-minutes: 60 # Increase this timeout value as needed
     env:
       HTTP_PROXY: ${{ secrets.PROXY_HTTP }}
@@ -164,9 +188,6 @@ jobs:
       NO_PROXY: "localhost,127.0.0.1,hf-mirror.com"
       HF_ENDPOINT: "https://hf-mirror.com"
       HF_HUB_ENABLE_HF_TRANSFER: "0" # This is more stable
-    container:
-      image: whatcanyousee/verl:ngc-cu124-vllm0.8.5-sglang0.4.6.post5-mcore0.12.0-te2.3
-      options: --gpus all --shm-size=10g
     steps:
       - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
         with:
@@ -195,7 +216,8 @@ jobs:
         run: |
           rm -rf checkpoints
   e2e_ppo_trainer_megatron-deepseek-override-transformer-config:
-    runs-on: [L20x8]
+    needs: setup
+    runs-on: ["${{ needs.setup.outputs.runner-label }}"]
     timeout-minutes: 60 # Increase this timeout value as needed
     env:
       HTTP_PROXY: ${{ secrets.PROXY_HTTP }}
@@ -203,9 +225,6 @@ jobs:
       NO_PROXY: "localhost,127.0.0.1,hf-mirror.com"
       HF_ENDPOINT: "https://hf-mirror.com"
       HF_HUB_ENABLE_HF_TRANSFER: "0" # This is more stable
-    container:
-      image: whatcanyousee/verl:ngc-cu124-vllm0.8.5-sglang0.4.6.post5-mcore0.12.0-te2.3
-      options: --gpus all --shm-size=10g
     steps:
       - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
         with:
@@ -229,7 +248,8 @@ jobs:
         run: |
           rm -rf checkpoints
   e2e_ppo_trainer_megatron-moe-expert-parallel:
-    runs-on: [L20x8]
+    needs: setup
+    runs-on: ["${{ needs.setup.outputs.runner-label }}"]
     timeout-minutes: 60 # Increase this timeout value as needed
     env:
       HTTP_PROXY: ${{ secrets.PROXY_HTTP }}
@@ -237,9 +257,6 @@ jobs:
       NO_PROXY: "localhost,127.0.0.1,hf-mirror.com"
       HF_ENDPOINT: "https://hf-mirror.com"
       HF_HUB_ENABLE_HF_TRANSFER: "0" # This is more stable
-    container:
-      image: whatcanyousee/verl:ngc-cu124-vllm0.8.5-sglang0.4.6.post5-mcore0.12.0-te2.3
-      options: --gpus all --shm-size=10g
     steps:
       - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
         with:
@@ -263,7 +280,8 @@ jobs:
         run: |
           rm -rf checkpoints
   e2e_ppo_trainer_megatron-qwen2_5vl-3b:
-    runs-on: [L20x8]
+    needs: setup
+    runs-on: ["${{ needs.setup.outputs.runner-label }}"]
     timeout-minutes: 60 # Increase this timeout value as needed
     env:
       HTTP_PROXY: ${{ secrets.PROXY_HTTP }}
@@ -271,9 +289,6 @@ jobs:
       NO_PROXY: "localhost,127.0.0.1,hf-mirror.com"
       HF_ENDPOINT: "https://hf-mirror.com"
       HF_HUB_ENABLE_HF_TRANSFER: "0" # This is more stable
-    container:
-      image: whatcanyousee/verl:ngc-cu124-vllm0.8.5-sglang0.4.6.post5-mcore0.12.0-te2.3
-      options: --gpus all --shm-size=10g
     steps:
       - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
         with:
@@ -294,3 +309,17 @@ jobs:
       - name: clean up
         run: |
           rm -rf checkpoints
+
+  cleanup: 
+    runs-on: ubuntu-latest  
+    needs: [setup,e2e_ppo_trainer_megatron-deepseek,e2e_ppo_trainer_megatron-qwen3,e2e_ppo_trainer_megatron-different-train-infer-tp-qwen-tie-embedding,
+    e2e_ppo_trainer_megatron-qwen-override-transformer-config,e2e_ppo_trainer_megatron-deepseek-override-transformer-config,e2e_ppo_trainer_megatron-moe-expert-parallel,
+    e2e_ppo_trainer_megatron-qwen2_5vl-3b]        
+    if: always()          
+    steps:
+      - name: remove runner
+        run: |
+           # 调用faas清理runner环境
+           resp=$(curl -X POST "${{ env.DYNAMIC_RUNNER_ENDPOINT }}/delete-test" \
+            -d '{"TaskId": "${{ needs.setup.outputs.mlp-task-id }}"}')
+           echo $resp
